USE [ioannisCerintORG]
GO

/****** Object:  Table [dbo].[Lessons]    Script Date: 26/07/2017 20:27:00  ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Lessons] (
    [lessonId]             INT            IDENTITY (1, 1) NOT NULL,
    [lessonTitleEN]        NVARCHAR (150) NOT NULL,
    [lessonTitleEL]        NVARCHAR (150) NOT NULL,
    [lessonSemester]       NVARCHAR (50)  DEFAULT ('') NOT NULL,
    [ECTS]                 FLOAT (53)     DEFAULT ((0)) NOT NULL,
    [lessonCodeDepartment] NVARCHAR (15)  DEFAULT ('') NOT NULL,
    CONSTRAINT [PK_dbo.Lessons] PRIMARY KEY CLUSTERED ([lessonId] ASC)
);

SET IDENTITY_INSERT[dbo].[Lessons] ON
INSERT INTO[dbo].[Lessons] (lessonId, lessonTitleEN, lessonTitleEl, lessonSemester, ECTS, lessonCodeDepartment) VALUES


(1, N'English Technical Terminology', N'Αγγλική Τεχνική Ορολογία', N'1o Εξάμηνο', 3, N'101ΓΥΥΚ'),
(2, N'Computer architecture', N'Αρχιτεκτονική Υπολογιστών', N'1o Εξάμηνο', 4, N'102ΓΥΥΚ'),
(3, N'discrete mathematics', N'Διακριτά Μαθηματικά', N'1o Εξάμηνο', 5, N'103ΓΥΥΚ'),
(4, N'Introduction to Programming', N'Εισαγωγή στον Προγραμματισμό', N'1o Εξάμηνο', 6, N'104ΓΥΥΚ'),
(5, N'Electric systems', N'Ηλεκτρικά Κυκλώματα', N'1o Εξάμηνο', 6, N'105ΓΥΥΚ'),
(6, N'Mathematics I', N'Μαθηματικά Ι', N'1o Εξάμηνο', 6, N'106ΓΥΥΚ'),
(7, N'Introduction to Databases', N'Εισαγωγή στις Βάσεις Δεδομένων', N'2o Εξάμηνο', 4, N'201ΕΥΥΚ'),
(8, N'Electronic circuits', N'Ηλεκτρονικά Κυκλώματα', N'2o Εξάμηνο', 6, N'202ΓΥΥΚ'),
(9, N'Theories of Learning and Teaching in Informatics', N'Θεωρίες Μάθησης και Διδασκαλίας στην Πληροφορική', N'2o Εξάμηνο', 5, N'203ΓΥΥΚ'),
(10, N'Mathematics II', N'Μαθηματικά ΙΙ', N'2o Εξάμηνο', 4, N'204ΓΥΥΚ'),
(11, N'Scientific Research Methodology', N'Μεθοδολογία Επιστημονικής Ερευνας', N'2o Εξάμηνο', 5, N'205ΓΥΥΚ'),
(12, N'Planning Techniques', N'Τεχνικές Προγραμματισμού', N'2o Εξάμηνο', 6, N'206ΕΥΥΚ'),
(13, N'Algorithms and Data Structures', N'Αλγόριθμοι και Δομές Δεδομένων', N'3o Εξάμηνο', 4, N'301ΕΥΥΚ'),
(14, N'Object-Oriented Programming', N'Αντικειμενοστραφής Προγραμματισμός', N'3o Εξάμηνο', 5, N'302ΕΥΥΚ'),
(15, N'Computer networks', N'Δίκτυα Υπολογιστών', N'3o Εξάμηνο', 5, N'303ΕΥΥΚ'),
(16, N'Introduction to Software Engineering', N'Εισαγωγή στην Τεχνολογία Λογισμικού', N'3o Εξάμηνο', 5, N'304ΕΥΥΚ'),
(17, N'Scientific Calculation', N'Επιστημονικός Υπολογισμός', N'3o Εξάμηνο', 4, N'305ΕΥΥΚ'),
(18, N'Digital systems', N'Ψηφιακά Συστήματα', N'3o Εξάμηνο', 7, N'306ΕΥΥΚ'),
(19, N'Introduction to Web Programming', N'Εισαγωγή στον Προγραμματισμό του Ιστού', N'4o Εξάμηνο', 6, N'401ΕΥΥΚ'),
(20, N'Educational Technologies', N'Εκπαιδευτικές Τεχνολογίες', N'4o Εξάμηνο', 5, N'402ΓΥΥΚ'),
(21, N'Institutions & Policies of the European Union', N'Θεσμοί & Πολιτικές της Ευρωπαϊκής Ένωσης', N'4o Εξάμηνο', 5, N'403ΓΥΥΚ'),
(22, N'Neural networks', N'Νευρωνικά Δίκτυα', N'4o Εξάμηνο', 4, N'404ΓΥΥΚ'),
(23, N'Artificial Intelligence', N'Τεχνητή Νοημοσύνη', N'4o Εξάμηνο', 5, N'405ΕΥΥΚ'),
(24, N'Digital image processing', N'Ψηφιακή Επεξεργασία Εικόνας', N'4o Εξάμηνο', 5, N'406ΓΥΥΚ'),
(25, N'Operating Systems', N'Λειτουργικά Συστήματα', N'5o Εξάμηνο', 5, N'501ΕΥΥΚ'),
(26, N'Compilers', N'Μεταγλωτιστές', N'5o Εξάμηνο', 5, N'502ΕΥΥΚ'),
(27, N'Signs and systems', N'Σήματα και Συστήματα', N'5o Εξάμηνο', 7, N'503ΕΥΥΚ'),
(28, N'Microcomputer Systems', N'Συστήματα Μικροϋπολογιστών', N'5o Εξάμηνο', 7, N'504ΕΥΥΚ'),
(29, N'Computational Intelligence', N'Υπολογιστική Νοημοσύνη', N'5o Εξάμηνο', 6, N'505ΕΥΥΚ'),
(30, N'Embedded Systems', N'Ενσωματωμένα Συστήματα', N'6o Εξάμηνο ΜΗΧΑΝΙΚΟΙ Η/Υ ΤΕ', 5, N'601ΕΔΥΑ'),
(31, N'Advanced Digital Design Applications', N'Προηγμένες Εφαρμογές Ψηφιακής Σχεδίασης', N'6o Εξάμηνο ΜΗΧΑΝΙΚΟΙ Η/Υ ΤΕ', 5, N'602ΕΔΜΑ'),
(32, N'Automatic control system', N'Συστήματα Αυτομάτου Ελέγχου', N'6o Εξάμηνο ΜΗΧΑΝΙΚΟΙ Η/Υ ΤΕ', 8, N'603ΕΔΥΑ'),
(33, N'Network Planning', N'Προγραμματισμός Δικτύων', N'6o Εξάμηνο ΜΗΧΑΝΙΚΟΙ ΔΙΚΤΥΩΝ ΤΕ', 6, N'604ΕΔΥΒ'),
(34, N'Protection and Security of Computer Systems', N'Προστασία και Ασφάλεια Συστημάτων Υπολογιστών', N'6o Εξάμηνο ΜΗΧΑΝΙΚΟΙ ΔΙΚΤΥΩΝ ΤΕ', 7, N'605ΕΔΜΒ'),
(35, N'Protocols and Internet Architectures', N'Πρωτόκολλα και Αρχιτεκτονικές Διαδικτύου', N'6o Εξάμηνο ΜΗΧΑΝΙΚΟΙ ΔΙΚΤΥΩΝ ΤΕ', 7, N'606ΕΔΜΒ'),
(36, N'Software Engineering - Software Quality', N'Διαχείριση Έργων Λογισμικού ? Ποιότητα Λογισμικού', N'6o Εξάμηνο ΜΗΧΑΝΙΚΟΙ ΛΟΓΙΣΜΙΚΟΥ ΤΕ', 8, N'607ΕΔΜΓ'),
(37, N'Logical Programming', N'Λογικός Προγραμματισμός', N'6o Εξάμηνο ΜΗΧΑΝΙΚΟΙ ΛΟΓΙΣΜΙΚΟΥ ΤΕ', 6, N'608ΕΔΥΓ'),
(38, N'User Interface Programming', N'Προγραμματισμός Διεπαφής Χρήστη', N'6o Εξάμηνο ΜΗΧΑΝΙΚΟΙ ΛΟΓΙΣΜΙΚΟΥ ΤΕ', 6, N'609ΕΔΜΓ'),
(39, N'Advanced Digital Design Applications', N'Προηγμένες Εφαρμογές Ψηφιακής Σχεδίασης', N'6o Εξάμηνο ΜΗΧΑΝΙΚΟΙ ΛΟΓΙΣΜΙΚΟΥ ΤΕ', 5, N'602ΕΔΜΑ'),
(40, N'Protection and Security of Computer Systems', N'Προστασία και Ασφάλεια Συστημάτων Υπολογιστών', N'6o Εξάμηνο Μαθήματα Επιλογής', 7, N'605ΕΔΜΒ'),
(41, N'Protocols and Internet Architectures', N'Πρωτόκολλα και Αρχιτεκτονικές Διαδικτύου', N'6o Εξάμηνο Μαθήματα Επιλογής', 7, N'606ΕΔΜΒ'),
(42, N'Software Engineering - Software Quality', N'Διαχείριση Έργων Λογισμικού ? Ποιότητα Λογισμικού', N'6o Εξάμηνο Μαθήματα Επιλογής', 8, N'607ΕΔΜΓ'),
(43, N'User Interface Programming', N'Προγραμματισμός Διεπαφής Χρήστη', N'6o Εξάμηνο Μαθήματα Επιλογής', 6, N'609ΕΔΜΓ'),
(44, N'Bioinformatics', N'Βιοπληροφορική', N'6o Εξάμηνο Μαθήματα Επιλογής', 5, N'611ΕΔΕΧ'),
(45, N'Computer Graphics', N'Γραφικά Υπολογιστών', N'6o Εξάμηνο Μαθήματα Επιλογής', 5, N'612ΕΔΕΧ'),
(46, N'Special Database Themes', N'Ειδικά Θέματα Βάσεων Δεδομένων', N'6o Εξάμηνο Μαθήματα Επιλογής', 5, N'613ΕΔΕΧ'),
(47, N'Applied Statistics', N'Εφαρμοσμένη Στατιστική', N'6o Εξάμηνο Μαθήματα Επιλογής', 3, N'614ΓΥΕΧ'),
(48, N'Information Systems Management', N'Πληροφοριακά Συστήματα Διοίκησης', N'6o Εξάμηνο Μαθήματα Επιλογής', 4, N'615ΓΥΕΧ'),
(49, N'Artificial Vision', N'Τεχνητή Όραση', N'6o Εξάμηνο Μαθήματα Επιλογής', 5, N'616ΕΔΕΧ'),
(50, N'Computational Nanotechnology Systems', N'Υπολογιστικά Συστήματα Νανοτεχνολογίας', N'6o Εξάμηνο Μαθήματα Επιλογής', 6, N'617ΕΔΕΧ'),
(51, N'Quality control', N'Διαχείριση Ποιότητας', N'6o Εξάμηνο Μαθήματα Επιλογής', 6, N'618ΕΔΕΧ'),
(52, N'Animated Robots and Applications', N'Κινούμενα Ρομπότ και Εφαρμογές', N'7o Εξάμηνο ΜΗΧΑΝΙΚΟΙ Η/Υ ΤΕ', 6, N'701ΕΔΜΑ'),
(53, N'Robotics and Human-Machine Interaction', N'Ρομποτική και Αλληλεπίδραση Ανθρώπου?Μηχανής', N'7o Εξάμηνο ΜΗΧΑΝΙΚΟΙ Η/Υ ΤΕ', 6, N'702ΕΔΥΑ'),
(54, N'Microprocessor Based Embedded Systems Technology', N'Τεχνολογια Ενσωματωμένων Συστημάτων Βασιζόμενων σε Μικροεπεξεργαστές', N'7o Εξάμηνο ΜΗΧΑΝΙΚΟΙ Η/Υ ΤΕ', 9, N'703ΕΔΜΑ'),
(55, N'Wireless Networks and Mobile Communications', N'Ασύρματα Δίκτυα και Κινητές Επικοινωνίες', N'7o Εξάμηνο ΜΗΧΑΝΙΚΟΙ ΔΙΚΤΥΩΝ ΤΕ', 5, N'704ΕΔΥΒ'),
(56, N'Security of Information Systems and Communications', N'Ασφάλεια Πληροφοριακών Συστημάτων και Επικοινωνιών', N'7o Εξάμηνο ΜΗΧΑΝΙΚΟΙ ΔΙΚΤΥΩΝ ΤΕ', 7, N'705ΕΔΜΒ'),
(57, N'Telematics and Broadband Networks', N'Τηλεματική και Ευρυζωνικά Δίκτυα', N'7o Εξάμηνο ΜΗΧΑΝΙΚΟΙ ΔΙΚΤΥΩΝ ΤΕ', 7, N'706ΕΔΜΒ'),
(58, N'Identify patterns', N'Αναγνώριση Προτύπων', N'7o Εξάμηνο ΜΗΧΑΝΙΚΟΙ ΛΟΓΙΣΜΙΚΟΥ ΤΕ', 6, N'708ΕΔΜΓ'),
(59, N'Parallel and Distributed Calculation', N'Παράλληλος και Κατανεμημένος Υπολογισμός', N'7o Εξάμηνο ΜΗΧΑΝΙΚΟΙ ΛΟΓΙΣΜΙΚΟΥ ΤΕ', 6, N'707ΕΔΜΓ'),
(60, N'Advanced mobile apps', N'Προηγμένες εφαρμογές κινητών συσκευών', N'7o Εξάμηνο ΜΗΧΑΝΙΚΟΙ ΛΟΓΙΣΜΙΚΟΥ ΤΕ', 7, N'709ΕΔΥΓ'),
(61, N'Animated Robots and Applications', N'Κινούμενα Ρομπότ και Εφαρμογές', N'7o Εξάμηνο Μαθήματα Επιλογής', 6, N'701ΕΔΜΑ'),
(62, N'Microprocessor Based Embedded Systems Technology', N'Τεχνολογια Ενσωματωμένων Συστημάτων Βασιζόμενων σε Μικροεπεξεργαστές', N'7o Εξάμηνο Μαθήματα Επιλογής', 9, N'703ΕΔΜΑ'),
(63, N'Security of Information Systems and Communications', N'Ασφάλεια Πληροφοριακών Συστημάτων και Επικοινωνιών', N'7o Εξάμηνο Μαθήματα Επιλογής', 7, N'705ΕΔΜΒ'),
(64, N'Telematics and Broadband Networks', N'Τηλεματική και Ευρυζωνικά Δίκτυα', N'7o Εξάμηνο Μαθήματα Επιλογής', 7, N'706ΕΔΜΒ'),
(65, N'Parallel and Distributed Calculation', N'Παράλληλος και Κατανεμημένος Υπολογισμός', N'7o Εξάμηνο Μαθήματα Επιλογής', 6, N'707ΕΔΜΓ'),
(66, N'Identify patterns', N'Αναγνώριση Προτύπων', N'7o Εξάμηνο Μαθήματα Επιλογής', 6, N'708ΕΔΜΓ'),
(67, N'Neural Architecture and Computer Grids', N'Αρχιτεκτονική Νεφών και Πλεγμάτων Η/Υ', N'7o Εξάμηνο Μαθήματα Επιλογής', 5, N'710ΕΔΕΧ'),
(68, N'Detecting Electronic Crime', N'Εξιχνίαση Ηλεκτρονικού Εγκλήματος', N'7o Εξάμηνο Μαθήματα Επιλογής', 4, N'711ΕΔΕΧ'),
(69, N'Business Decisions and Functions', N'Επιχειρηματικές Αποφάσεις και Λειτουργίες', N'7o Εξάμηνο Μαθήματα Επιλογής', 6, N'712ΓΥΕΧ'),
(70, N'Business Intelligence', N'Μηχανοργάνωση Επιχειρήσεων', N'7o Εξάμηνο Μαθήματα Επιλογής', 4, N'713ΓΥΕΧ'),
(71, N'Multimedia', N'Πολυμέσα', N'7o Εξάμηνο Μαθήματα Επιλογής', 4, N'714ΕΔΕΧ'),
(72, N'Networks of the World Wide Web', N'Δίκτυα του Παγκόσμιου Ιστού', N'7o Εξάμηνο Μαθήματα Επιλογής', 3, N'715ΕΔΕΧ'),
(73, N'Industrial Design', N'Βιομηχανικό Σχέδιο', N'7o Εξάμηνο Μαθήματα Επιλογής', 6, N'716ΕΔΕΧ'),
(74, N'Industrial Unit Simulations', N'Προσομοιώσεις Βιομηχανικών Μονάδων', N'7o Εξάμηνο Μαθήματα Επιλογής', 6, N'717ΕΔΕΧ'),
(75, N'Workshop', N'Πρακτική Άσκηση', N'8o Εξάμηνο', 10, N'(ΠΡΑΚ)'),
(76, N'Thesis', N'Πτυχιακή Εργασία', N'8o Εξάμηνο', 20, N'(ΠΤΥΧ)'),
(77, N'Macroeconomic Analysis', N'Μακροοικονομική Ανάλυση', N'1o Εξάμηνο', 5, N'ΝΚΟΙ3101'),
(78, N'Microeconomic Analysis', N'Μικροοικονομική Ανάλυση', N'1o Εξάμηνο', 5, N'ΝΚΟΙ3204'),
(79, N'Mathematics in Management', N'Μαθηματικά στη Διοίκηση', N'1o Εξάμηνο', 5, N'ΝΚΜΑ0401'),
(80, N'Financial Accounting I', N'Χρηματοοικονομική Λογιστική Ι', N'1o Εξάμηνο', 5, N'NKΛΟ1201'),
(81, N'Information Technology', N'Τεχνολογία Πληροφορικής ', N'1o Εξάμηνο', 5, N'NKΗΥ0300'),
(82, N'Business Statistics', N'Στατιστική Επιχειρήσεων', N'1o Εξάμηνο', 5, N'ΝΚΣΤ0300'),
(83, N'Management', N'Μάνατζμεντ', N'2o Εξάμηνο', 5, N'ΝΚΔΕ0001'),
(84, N'Statistical Forecasting Methods', N'Στατιστικές Μέθοδοι Πρόβλεψης', N'2o Εξάμηνο', 5, N'ΝΚΣΤ401'),
(85, N'Databases', N'Βάσεις Δεδομένων', N'2o Εξάμηνο', 5, N'ΝΚΗΥ1006'),
(86, N'Marketing principles', N'Αρχές Marketing', N'2o Εξάμηνο', 5, N'ΝΚΜΑ4001'),
(87, N'Financial Accounting II', N'Χρηματοοικονομική Λογιστική ΙΙ', N'2o Εξάμηνο', 5, N'ΝΚΛΟ1202'),
(88, N'Operating Systems (Cat: IPS)', N'Λειτουργικά Συστήματα (Κατ: ΔΠΣ)', N'2o Εξάμηνο', 5, N'(ΔΠΣ)ΗΥ1005'),
(89, N'Foreign Language - English Terminology ', N'Ξένη γλώσσα - Αγγλική Ορολογία (Κατ: ΔΕ & ΜΑΡΚ)', N'2o Εξάμηνο', 5, N'(ΔΕΜ)ΓΕ1900'),
(90, N'Information and Communication Management ', N'Πληροφορία και Διαχείριση της Επικοινωνίας (Κατ: ΔΕ & ΜΑΡΚ)', N'2o Εξάμηνο', 5, N'(ΔΕΜ)ΔΕ5000'),
(91, N'Human resource Management', N'Διοίκηση Ανθρώπινων Πόρων', N'3o Εξάμηνο', 5, N'NKΕ1600'),
(92, N'Project management', N'Διαχείριση Έργων', N'3o Εξάμηνο', 5, N'ΝΚΓΕ1803'),
(93, N'Consumers behavior', N'Συμπεριφορά Καταναλωτή', N'3o Εξάμηνο', 5, N'ΝΚΓΕ2800'),
(94, N'Management Information Systems', N'Συστήματα Πληροφοριών Διοίκησης', N'3o Εξάμηνο', 5, N'ΝΚΗΥ0501'),
(95, N'Supply Chain Management', N'Διοίκηση Εφοδιαστικής Αλυσίδας', N'3o Εξάμηνο', 5, N'ΝΚΔΕ4000'),
(96, N'Computer architecture', N'Αρχιτεκτονική Υπολογιστών (Κατ: ΔΠΣ)', N'3o Εξάμηνο', 5, N'(ΔΠΣ) ΗΥ1000'),
(97, N'Administrative Accounting I', N'Διοικητική Λογιστική Ι (Κατ: ΔΕ & ΜΑΡΚ)', N'3o Εξάμηνο', 5, N'(ΔΕΜ)ΛΟ1501'),
(98, N'Financial management', N'Χρηματοοικονομική Διοίκηση', N'4o Εξάμηνο', 5, N'ΝΚΧΡ4002'),
(99, N'Management in the Public Sector', N'Μάνατζμεντ στο Δημόσιο Τομέα ', N'4o Εξάμηνο', 5, N'NKΔΕ0000'),
(100, N'EBusiness', N'Ηλεκτρονικό Επιχειρείν', N'4o Εξάμηνο', 5, N'ΝΚΗΥ901'),
(101, N'Total Quality Management - Quality Control', N'Διοίκηση Ολικής Ποιότητας - Ποιοτικός Έλεγχος', N'4o Εξάμηνο', 5, N'ΝΚΓΕ3202'),
(102, N'Entrepreneurship', N'Επιχειρηματικότητα', N'4o Εξάμηνο', 5, N'ΝΚΓΕ2200'),
(103, N'International Economic Relations', N'Διεθνείς Οικονομικές Σχέσεις (Κατ: ΔΕ)', N'4o Εξάμηνο', 5, N'(ΔΕ)ΟΙ3300'),
(104, N'Multimedia', N'Πολυμέσα (Κατ: ΔΠΣ)', N'4o Εξάμηνο', 5, N'(ΔΠΣ)ΗΥ1002'),
(105, N'Communication & Advertising', N'Επικοινωνία & Διαφήμιση (Κατ: ΜΑΡΚ)', N'4o Εξάμηνο', 5, N'(ΜΚ)ΔΕ1801'),
(106, N'Strategic Management', N'Στρατηγική Διοίκηση', N'5o Εξάμηνο', 6, N'ΝΚΔΕ1700'),
(107, N'Marketing Services', N'Marketing Υπηρεσιών (Κατ: ΔΕ & ΜΑΡΚ)', N'5o Εξάμηνο', 6, N'(ΜΚ)ΓΕ2905'),
(108, N'Structured Programming', N'Δομημένος Προγραμματισμός (Κατ: ΔΠΣ)', N'5o Εξάμηνο', 6, N'(ΔΠΣ)ΗΥ0600'),
(109, N'Innovation Management', N'Διαχείριση Καινοτομιών (Κατ: ΔΕ)', N'5o Εξάμηνο', 6, N'(ΔΕ)ΓΕ3900'),
(110, N'Expert Systems and Decision Support Systems', N'Έμπειρα Συστήματα και Συστήματα Υποστήριξης Αποφάσεων (Κατ: ΔΠΣ)', N'5o Εξάμηνο', 6, N'(ΔΠΣ)ΓΕ4000'),
(111, N'Marketing of Agricultural Products, Food & Drink', N'Marketing Αγροτικών Προϊόντων, Τροφίμων & Ποτών (Κατ: ΜΑΡΚ)', N'5o Εξάμηνο', 6, N'(ΜΚ)ΓΕ2901'),
(112, N'Funding and Evaluation of Investment Plans', N'Χρηματοδότηση και Αξιολόγηση Επενδυτικών Σχεδίων (Κατ: ΔΕ)', N'5o Εξάμηνο', 6, N'(ΔΕ)ΧΡ4001'),
(113, N'Computer networks', N'Δίκτυα Υπολογιστών (Κατ: ΔΠΣ)', N'5o Εξάμηνο', 6, N'(ΔΠΣ)ΗΥ1004'),
(114, N'Social Marketing', N'Κοινωνικό Marketing (Κατ: ΜΑΡΚ)', N'5o Εξάμηνο', 6, N'(ΜΚ)ΓΕ2903'),
(115, N'Organisational Behaviour', N'Οργανωσιακή Συμπεριφορά (Κατ: ΔΕ)', N'5o Εξάμηνο', 6, N'(ΔΕ)ΓΕ1800'),
(116, N'Discrete Mathematics - Linear Algebra', N'Διακριτά Μαθηματικά - Γραμμική Άλγεβρα (Κατ: ΔΠΣ)', N'5o Εξάμηνο', 6, N'(ΔΠΣ)ΜΑ3303'),
(117, N'International Marketing', N'Διεθνές Marketing (Κατ: ΜΑΡΚ)', N'5o Εξάμηνο', 6, N'(ΜΚ)ΓΕ2904'),
(118, N'Commercial law', N'Εμπορικό Δίκαιο', N'6o Εξάμηνο', 5, N'NKΔΙ0301'),
(119, N'European Integration', N'Ευρωπαϊκή Ολοκλήρωση (Κατ: ΔΕ & ΜΑΡΚ)', N'6o Εξάμηνο', 5, N'(ΔΕΜ)ΔΙ0501'),
(120, N'Data structures', N'Δομές Δεδομένων (Κατ: ΔΠΣ)', N'6o Εξάμηνο', 5, N'(ΔΠΣ)ΗΥ1003'),
(121, N'Knowledge management', N'Διαχείριση Γνώσης (Κατ: ΔΕ)', N'6o Εξάμηνο', 5, N'(ΔΕ)ΓΕ1801'),
(122, N'Object-Oriented Design and Programming', N'Αντικειμενοστρεφής Σχεδιασμός και Προγραμματισμός (Κατ: ΔΠΣ)', N'6o Εξάμηνο', 5, N'(ΔΠΣ)ΗΥ0802'),
(123, N'Strategic Marketing', N'Στρατηγικό Marketing (Κατ: ΜΑΡΚ)', N'6o Εξάμηνο', 5, N'(ΜΚ)ΜΚ3202'),
(124, N'Administrative Accounting II', N'Διοικητική Λογιστική ΙΙ (Κατ: ΔΕ)', N'6o Εξάμηνο', 5, N'(ΔΕ)ΛΟ1402'),
(125, N'Operational research', N'Επιχειρησιακή Έρευνα (Κατ: ΔΠΣ)', N'6o Εξάμηνο', 5, N'(ΔΠΣ)ΓΕ3001'),
(126, N'Industrial Marketing', N'Βιομηχανικό Marketing (Κατ: ΜΑΡΚ)', N'6o Εξάμηνο', 5, N'(ΜΚ)ΜΚ3204'),
(127, N'Financial Modeling', N'Χρηματοοικονομική Μοντελοποίηση (Κατ: ΔΕ)', N'6o Εξάμηνο', 5, N'(ΔΕ)ΧΡ3400'),
(128, N'Security of Systems', N'Ασφάλεια Συστημάτων (Κατ: ΔΠΣ)', N'6o Εξάμηνο', 5, N'(ΔΠΣ)ΗΥ1012'),
(129, N'Marketing of Wholesale and Retail Trade', N'Marketing Χονδρικού και Λιανικού Εμπορίου (Κατ: ΜΑΡΚ)', N'6o Εξάμηνο', 5, N'(ΜΚ)ΓΕ3206'),
(130, N'Management of Production Systems', N'Διοίκηση Παραγωγικών Συστημάτων (Κατ: ΔΕ)', N'6o Εξάμηνο', 5, N'(ΔΕ)ΔΕ4001'),
(131, N'Systems Analysis - Software Engineering', N'Ανάλυση Συστημάτων - Τεχνολογία Λογισμικού (Κατ: ΔΠΣ)', N'6o Εξάμηνο', 5, N'(ΔΠΣ)ΗΥ1008'),
(132, N'New Product Development and Pricing Strategy', N'Ανάπτυξη νέων Προϊόντων και Στρατηγική Τιμολόγησης (Κατ: ΜΑΡΚ)', N'6o Εξάμηνο', 5, N'(ΜΚ)ΓΕ2906'),
(133, N'Wise Seminar - Methodology of Epistonomic Research', N'Σεμινάριο Τελειοφοίτων - Μεθοδολογία Επιστιμονικής Έρευνας', N'7o Εξάμηνο', 6, N'ΝΚΓΕ2601'),
(134, N'Corporate Responsibility & Ethics', N'Εταιρική Ευθύνη & Ηθική (Κατ: ΔΕ & ΜΑΡΚ)', N'7o Εξάμηνο', 6, N'(ΔΕΜ)ΓΕ3401'),
(135, N'Advanced Computer Themes or Electronic Criminology', N'Προηγμένα Θέματα Πληροφορικής (Κατ: ΔΠΣ) ή Ηλεκτρονική Εγκληματολογία (Κατ: ΔΠΣ)', N'7o Εξάμηνο', 6, N'ΔΠΣ-ΗΥ1010/2001'),
(136, N'Labor law', N'Εργατικό Δίκαιο (Κατ: ΔΕ)', N'7o Εξάμηνο', 6, N'(ΔΕ)ΔΙ401'),
(137, N'Development of Computer Applications', N'Ανάπτυξη Υπολογιστικών Εφαρμογών (Κατ: ΔΠΣ)', N'7o Εξάμηνο', 6, N'(ΔΠΣ)ΗΥ2002'),
(138, N'Tourism Marketing', N'Marketing Τουρισμού (Κατ: ΜΑΡΚ)', N'7o Εξάμηνο', 6, N'(ΜΚ)ΜΚ4001'),
(139, N'Market Research', N'Έρευνα Αγοράς (Κατ: ΔΕ & ΜΑΡΚ)', N'7o Εξάμηνο', 6, N'(ΔΕΜ)ΓΕ2902'),
(140, N'Graphics', N'Γραφικά (Κατ: ΔΠΣ)', N'7o Εξάμηνο', 6, N'(ΔΠΣ)ΗΥ2000'),
(141, N'Special Topics in Finance', N'Ειδικά Θέματα Χρηματοοικονομικής (Κατ: ΔΕ)', N'7o Εξάμηνο', 6, N'(ΔΕ)ΧΡ6000'),
(142, N'Visual Programming - Interface Design', N'Οπτικός Προγραμματισμός - Σχεδίαση Διεπαφών (Κατ: ΔΠΣ)', N'7o Εξάμηνο', 6, N'(ΔΠΣ)ΓΕ500'),
(143, N'Sales Promotion & Public Relations', N'Προώθηση Πωλήσεων & Δημόσιες Σχέσεις (Κατ: ΜΑΡΚ)', N'7o Εξάμηνο', 6, N'(ΜΚ)ΜΚ3205'),
(144, N'Workshop', N'Πρακτική Άσκηση', N'8o Εξάμηνο', 10, N'ΓΕ0026'),
(145, N'Thesis', N'Πτυχιακή Εργασία', N'8o Εξάμηνο', 20, N'ΓΕ0025'),
(146, N'MICROECONOMICS', N'ΜΙΚΡΟΟΙΚΟΝΟΜΙΚΗ', N'1o Εξάμηνο - Παλαιό', 5, N'N/A'),
(147, N'MATHEMATICAL - QUANTITATIVE METHODS OF BUSINESS ADMINISTRATION', N'ΜΑΘΗΜΑΤΙΚΑ - ΠΟΣΟΤΙΚΕΣ ΜΕΘΟΔΟΙ ΔΙΟΙΚΗΣΗΣ ΕΠΙΧΕΙΡΗΣΕΩΝ', N'1o Εξάμηνο - Παλαιό', 5, N'N/A'),
(148, N'MANAGING IN THE PRIVATE AND PUBLIC SECTOR', N'ΜΑΝΑΤΖΜΕΝΤ ΣΤΟΝ ΙΔΙΩΤΙΚΟ ΚΑΙ ΔΗΜΟΣΙΟ ΤΟΜΕΑ', N'1o Εξάμηνο - Παλαιό', 5, N'N/A'),
(149, N'FINANCIAL ACCOUNTING Ι', N'ΧΡΗΜΑΤΟΟΙΚΟΝΟΜΙΚΗ ΛΟΓΙΣΤΙΚΗ Ι', N'1o Εξάμηνο - Παλαιό', 5, N'N/A'),
(150, N'INFORMATION TECHNOLOGY', N'ΤΕΧΝΟΛΟΓΙΑ ΠΛΗΡΟΦΟΡΙΚΗΣ', N'1o Εξάμηνο - Παλαιό', 4, N'N/A'),
(151, N'INTRODUCTION TO BUSINESS STATISTICS', N'ΕΙΣΑΓΩΓΗ ΣΤΗ ΣΤΑΤΙΣΤΙΚΗ ΤΩΝ ΕΠΙΧΕΙΡΗΣΕΩΝ', N'1o Εξάμηνο - Παλαιό', 6, N'N/A'),
(152, N'MACROECONOMICS', N'ΜΑΚΡΟΟΙΚΟΝΟΜΙΚΗ', N'2o Εξάμηνο - Παλαιό', 4, N'N/A'),
(153, N'FILE MANAGEMENT', N'ΔΙΑΧΕΙΡΙΣΗ ΑΡΧΕΙΩΝ', N'2o Εξάμηνο - Παλαιό', 4, N'N/A'),
(154, N'EUROPEAN INTEGRATION', N'ΕΥΡΩΠΑΪΚΗ ΟΛΟΚΛΗΡΩΣΗ', N'2o Εξάμηνο - Παλαιό', 4, N'N/A'),
(155, N'commercial law', N'ΕΜΠΟΡΙΚΟ ΔΙΚΑΙΟ', N'2o Εξάμηνο - Παλαιό', 6, N'N/A'),
(156, N'labor law', N'ΕΡΓΑΤΙΚΟ ΔΙΚΑΙΟ', N'2o Εξάμηνο - Παλαιό', 6, N'N/A'),
(157, N'FINANCIAL ACCOUNTING II', N'ΧΡΗΜΑΤΟΟΙΚΟΝΟΜΙΚΗ ΛΟΓΙΣΤΙΚΗ ΙΙ', N'2o Εξάμηνο - Παλαιό', 6, N'N/A'),
(158, N'human resource Management', N'ΔΙΟΙΚΗΣΗ ΑΝΘΡΩΠΙΝΩΝ ΠΟΡΩΝ', N'3o Εξάμηνο - Παλαιό', 5, N'N/A'),
(159, N'ENTREPRENEURSHIP - CREATIVITY', N'ΕΠΙΧΕΙΡΗΜΑΤΙΚΟΤΗΤΑ - ΔΗΜΙΟΥΡΓΙΚΟΤΗΤΑ', N'3o Εξάμηνο - Παλαιό', 5, N'N/A'),
(160, N'ADMINISTRATIVE ACCOUNTING Ι', N'ΔΙΟΙΚΗΤΙΚΗ ΛΟΓΙΣΤΙΚΗ Ι', N'3o Εξάμηνο - Παλαιό', 5, N'N/A'),
(161, N'MARKETING PRINCIPLES', N'ΑΡΧΕΣ MARKETING', N'3o Εξάμηνο - Παλαιό', 5, N'N/A'),
(162, N'ADMINISTRATIVE INFORMATION SYSTEMS', N'ΣΥΣΤΗΜΑΤΑ ΠΛΗΡΟΦΟΡΙΩΝ ΔΙΟΙΚΗΣΗΣ', N'3o Εξάμηνο - Παλαιό', 5, N'N/A'),
(163, N'ADMINISTRATION OF LOGISTICS', N'ΔΙΟΙΚΗΣΗ ΕΦΟΔΙΑΣΤΙΚΗΣ ΑΛΥΣΙΔΑΣ (LOGISTICS)', N'3o Εξάμηνο - Παλαιό', 5, N'N/A'),
(164, N'Taxation', N'ΦΟΡΟΤΕΧΝΙΚΑ', N'4o Εξάμηνο - Παλαιό', 8, N'N/A'),
(165, N'financial management', N'ΧΡΗΜΑΤΟΟΙΚΟΝΟΜΙΚΗ ΔΙΟΙΚΗΣΗ', N'4o Εξάμηνο - Παλαιό', 6, N'N/A'),
(166, N'MANAGEMENT OF PRODUCTION - FUNCTIONS', N'ΔΙΟΙΚΗΣΗ ΠΑΡΑΓΩΓΗΣ - ΛΕΙΤΟΥΡΓΙΩΝ', N'4o Εξάμηνο - Παλαιό', 6, N'N/A'),
(167, N'CONSUMER BEHAVIOR', N'ΣΥΜΠΕΡΙΦΟΡΑ ΤΟΥ ΚΑΤΑΝΑΛΩΤΗ', N'4o Εξάμηνο - Παλαιό', 5, N'N/A'),
(168, N'ADMINISTRATIVE ACCOUNT II', N'ΔΙΟΙΚΗΤΙΚΗ ΛΟΓΙΣΤΙΚΗ ΙΙ', N'4o Εξάμηνο - Παλαιό', 5, N'N/A'),
(169, N'STRATEGIC BUSINESS ADMINISTRATION', N'ΣΤΡΑΤΗΓΙΚΗ ΔΙΟΙΚΗΣΗ ΕΠΙΧΕΙΡΗΣΕΩΝ', N'5o Εξάμηνο - Παλαιό', 6, N'N/A'),
(170, N'ORGANISATIONAL BEHAVIOUR', N'ΟΡΓΑΝΩΣΙΑΚΗ ΣΥΜΠΕΡΙΦΟΡΑ', N'5o Εξάμηνο - Παλαιό', 6, N'N/A'),
(171, N'FOREIGN LANGUAGE (ENGLISH TERMINOLOGY)', N'ΞΕΝΗ ΓΛΩΣΣΑ (ΑΓΓΛΙΚΗ ΟΡΟΛΟΓΙΑ)', N'5o Εξάμηνο - Παλαιό', 7, N'N/A'),
(172, N'BUSINESS STATISTICS (SAMPLES)', N'ΣΤΑΤΙΣΤΙΚΗ ΤΩΝ ΕΠΙΧΕΙΡΗΣΕΩΝ (ΔΕΙΓΜΑΤΟΛΗΨΙΕΣ)', N'5o Εξάμηνο - Παλαιό', 6, N'N/A'),
(173, N'International Economic Relations', N'ΔΙΕΘΝΕΙΣ ΟΙΚΟΝΟΜΙΚΕΣ ΣΧΕΣΕΙΣ', N'5o Εξάμηνο - Παλαιό', 5, N'N/A'),
(174, N'corporate social responsibility', N'ΕΤΑΙΡΙΚΗ ΚΟΙΝΩΝΙΚΗ ΕΥΘΥΝΗ', N'6o Εξάμηνο - Παλαιό', 5, N'N/A'),
(175, N'TOTAL QUALITY MANAGEMENT - QUALITY CONTROL', N'ΔΙΟΙΚΗΣΗ ΟΛΙΚΗΣ ΠΟΙΟΤΗΤΑΣ - ΠΟΙΟΤΙΚΟΣ ΕΛΕΓΧΟΣ', N'6o Εξάμηνο - Παλαιό', 5, N'N/A'),
(176, N'MANAGEMENT OF INNOVATIONS', N'ΔΙΑΧΕΙΡΙΣΗ ΚΑΙΝΟΤΟΜΙΩΝ', N'6o Εξάμηνο - Παλαιό', 5, N'N/A'),
(177, N'ECONOMIC STUDIES', N'ΟΙΚΟΝΟΜΟΤΕΧΝΙΚΕΣ ΜΕΛΕΤΕΣ', N'6o Εξάμηνο - Παλαιό', 5, N'N/A'),
(178, N'ORGANIZATION & ADMINISTRATION OF HOSPITALITY & RECREATION', N'ΟΡΓΑΝΩΣΗ & ΔΙΟΙΚΗΣΗ ΕΠΙΧΕΙΡΗΣΕΩΝ ΦΙΛΟΞΕΝΙΑΣ & ΑΝΑΨΥΧΗΣ', N'6o Εξάμηνο - Παλαιό', 5, N'N/A'),
(179, N'ELECTRONIC COMMUNICATION - TRADE', N'ΗΛΕΚΤΡΟΝΙΚΗ ΕΠΙΚΟΙΝΩΝΙΑ - ΕΜΠΟΡΙΟ', N'6o Εξάμηνο - Παλαιό', 5, N'N/A'),
(180, N'COMMUNICATION AND ADVERTISING', N'ΕΠΙΚΟΙΝΩΝΙΑ ΚΑΙ ΔΙΑΦΗΜΙΣΗ', N'6o Εξάμηνο - Παλαιό', 5, N'N/A'),
(181, N'SPORTING MANATZMENT', N'ΑΘΛΗΤΙΚΟ MANATZMENT', N'6o Εξάμηνο - Παλαιό', 5, N'N/A'),
(182, N'SEMINAR OF UNDERGRADUATE - SCIENTIFIC RESEARCH METHODOLOGY', N'ΣΕΜΙΝΑΡΙΟ ΤΕΛΕΙΟΦΟΙΤΩΝ - ΜΕΘΟΔΟΛΟΓΙΑ ΕΠΙΣΤΗΜΟΝΙΚΗΣ ΕΡΕΥΝΑΣ', N'7o Εξάμηνο - Παλαιό', 6, N'N/A'),
(183, N'KNOWLEDGE MANAGEMENT', N'ΔΙΑΧΕΙΡΙΣΗ ΓΝΩΣΗΣ (KNOWLEDGE MANAGEMENT)', N'7o Εξάμηνο - Παλαιό', 6, N'N/A'),
(184, N'PROJECT MANAGEMENT', N'ΔΙΑΧΕΙΡΙΣΗ ΕΡΓΩΝ (PROJECT MANAGEMENT)', N'7o Εξάμηνο - Παλαιό', 6, N'N/A'),
(185, N'IMPLEMENTATION OF ADMINISTRATIVE DECISIONS ON PRODUCTION', N'ΕΦΑΡΜΟΓΗ ΔΙΟΙΚΗΤΙΚΩΝ ΑΠΟΦΑΣΕΩΝ ΣΤΗΝ ΠΑΡΑΓΩΓΗ', N'7o Εξάμηνο - Παλαιό', 6, N'N/A'),
(186, N'FINANCIAL MODELING', N'ΧΡΗΜΑΤΟΟΙΚΟΝΟΜΙΚΗ ΜΟΝΤΕΛΟΠΟΙΗΣΗ', N'7o Εξάμηνο - Παλαιό', 6, N'N/A'),
(187, N'Market Research', N'ΕΡΕΥΝΑ ΑΓΟΡΑΣ', N'7o Εξάμηνο - Παλαιό', 6, N'N/A'),
(188, N'MARKETING SERVICES (TOURIST MARKETING)', N'ΜΑΡΚΕΤΙΝΓΚ ΥΠΗΡΕΣΙΩΝ (ΤΟΥΡΙΣΤΙΚΟ ΜΑΡΚΕΤΙΝΓΚ)', N'7o Εξάμηνο - Παλαιό', 6, N'N/A'),
(189, N'Macroeconomic Analysis', N'Μακροοικονομική Ανάλυση', N'1o Εξάμηνο - κατ: ΔΠΣ', 5, N'ΝΚΟΙ3101'),
(190, N'Microeconomic Analysis', N'Μικροοικονομική Ανάλυση', N'1o Εξάμηνο - κατ: ΔΠΣ', 5, N'ΝΚΟΙ3204'),
(191, N'Mathematics in Management', N'Μαθηματικά στη Διοίκηση', N'1o Εξάμηνο - κατ: ΔΠΣ', 5, N'ΝΚΜΑ0401'),
(192, N'Financial Accounting I', N'Χρηματοοικονομική Λογιστική Ι', N'1o Εξάμηνο - κατ: ΔΠΣ', 5, N'NKΛΟ1201'),
(193, N'Information Technology', N'Τεχνολογία Πληροφορικής', N'1o Εξάμηνο - κατ: ΔΠΣ', 5, N'NKΗΥ0300'),
(194, N'Business Statistics', N'Στατιστική Επιχειρήσεων', N'1o Εξάμηνο - κατ: ΔΠΣ', 5, N'ΝΚΣΤ0300'),
(195, N'Management', N'Μάνατζμεντ', N'2o Εξάμηνο - κατ: ΔΠΣ', 5, N'ΝΚΔΕ0001'),
(196, N'Statistical Forecasting Methods', N'Στατιστικές Μέθοδοι Πρόβλεψης', N'2o Εξάμηνο - κατ: ΔΠΣ', 5, N'ΝΚΣΤ401'),
(197, N'Databases', N'Βάσεις Δεδομένων', N'2o Εξάμηνο - κατ: ΔΠΣ', 5, N'ΝΚΗΥ1006'),
(198, N'Marketing principles', N'Αρχές Marketing', N'2o Εξάμηνο - κατ: ΔΠΣ', 5, N'ΝΚΜΑ4001'),
(199, N'Financial Accounting II', N'Χρηματοοικονομική Λογιστική ΙΙ', N'2o Εξάμηνο - κατ: ΔΠΣ', 5, N'ΝΚΛΟ1202'),
(200, N'Operating Systems', N'Λειτουργικά Συστήματα', N'2o Εξάμηνο - κατ: ΔΠΣ', 5, N'(ΔΠΣ)ΗΥ1005'),
(201, N'Human resource Management', N'Διοίκηση Ανθρώπινων Πόρων', N'3o Εξάμηνο - κατ: ΔΠΣ', 5, N'NKΕ1600'),
(202, N'Project management', N'Διαχείριση Έργων', N'3o Εξάμηνο - κατ: ΔΠΣ', 5, N'ΝΚΓΕ1803'),
(203, N'Consumers behavior', N'Συμπεριφορά Καταναλωτή', N'3o Εξάμηνο - κατ: ΔΠΣ', 5, N'ΝΚΓΕ2800'),
(204, N'Management Information Systems', N'Συστήματα Πληροφοριών Διοίκησης', N'3o Εξάμηνο - κατ: ΔΠΣ', 5, N'ΝΚΗΥ0501'),
(205, N'Supply Chain Management', N'Διοίκηση Εφοδιαστικής Αλυσίδας', N'3o Εξάμηνο - κατ: ΔΠΣ', 5, N'ΝΚΔΕ4000'),
(206, N'Computer architecture', N'Αρχιτεκτονική Υπολογιστών', N'3o Εξάμηνο - κατ: ΔΠΣ', 5, N'(ΔΠΣ)ΗΥ1000'),
(207, N'Financial management', N'Χρηματοοικονομική Διοίκηση', N'4o Εξάμηνο - κατ: ΔΠΣ', 5, N'ΝΚΧΡ4002'),
(208, N'Management in the Public Sector', N'Μάνατζμεντ στο Δημόσιο Τομέα', N'4o Εξάμηνο - κατ: ΔΠΣ', 5, N'NKΔΕ0000'),
(209, N'EBusiness', N'Ηλεκτρονικό Επιχειρείν', N'4o Εξάμηνο - κατ: ΔΠΣ', 5, N'ΝΚΗΥ901'),
(210, N'Total Quality Management - Quality Control', N'Διοίκηση Ολικής Ποιότητας - Ποιοτικός Έλεγχος', N'4o Εξάμηνο - κατ: ΔΠΣ', 5, N'ΝΚΓΕ3202'),
(211, N'Entrepreneurship', N'Επιχειρηματικότητα', N'4o Εξάμηνο - κατ: ΔΠΣ', 5, N'ΝΚΓΕ2200'),
(212, N'Multimedia', N'Πολυμέσα', N'4o Εξάμηνο - κατ: ΔΠΣ', 5, N'(ΔΠΣ)ΗΥ1002'),
(213, N'Strategic Management', N'Στρατηγική Διοίκηση', N'5o Εξάμηνο - κατ: ΔΠΣ', 6, N'ΝΚΔΕ1700'),
(214, N'Structured Programming', N'Δομημένος Προγραμματισμός', N'5o Εξάμηνο - κατ: ΔΠΣ', 6, N'(ΔΠΣ)ΗΥ0600'),
(215, N'Experienced Decision Support Systems and Systems', N'Έμπειρα Συστήματα και Συστήματα Υποστήριξης Αποφάσεων', N'5o Εξάμηνο - κατ: ΔΠΣ', 6, N'(ΔΠΣ)ΓΕ4000'),
(216, N'Computer networks', N'Δίκτυα Υπολογιστών', N'5o Εξάμηνο - κατ: ΔΠΣ', 6, N'(ΔΠΣ)ΗΥ1004'),
(217, N'Discrete Mathematics - Linear Algebra', N'Διακριτά Μαθηματικά  - Γραμμική Άλγεβρα', N'5o Εξάμηνο - κατ: ΔΠΣ', 6, N'(ΔΠΣ)ΜΑ3303'),
(218, N'Commercial law', N'Εμπορικό Δίκαιο', N'6o Εξάμηνο - κατ: ΔΠΣ', 5, N'NKΔΙ0301'),
(219, N'Data structures', N'Δομές Δεδομένων', N'6o Εξάμηνο - κατ: ΔΠΣ', 5, N'(ΔΠΣ)ΗΥ1003'),
(220, N'Object-Oriented Design and Programming', N'Αντικειμενοστρεφής Σχεδιασμός και Προγραμματισμός', N'6o Εξάμηνο - κατ: ΔΠΣ', 5, N'(ΔΠΣ)ΗΥ0802'),
(221, N'Operational research', N'Επιχειρησιακή Έρευνα', N'6o Εξάμηνο - κατ: ΔΠΣ', 5, N'(ΔΠΣ)ΓΕ3001'),
(222, N'Security of Systems', N'Ασφάλεια Συστημάτων', N'6o Εξάμηνο - κατ: ΔΠΣ', 5, N'(ΔΠΣ)ΗΥ1012'),
(223, N'Systems Analysis - Software Engineering', N'Ανάλυση Συστημάτων - Τεχνολογία Λογισμικού', N'6o Εξάμηνο - κατ: ΔΠΣ', 5, N'(ΔΠΣ)ΗΥ1008'),
(224, N'SEMINAR OF UNDERGRADUATE - SCIENTIFIC RESEARCH METHODOLOGY', N'Σεμινάριο Τελειοφοίτων - Μεθοδολογία Επιστημονικής Έρευνας', N'7o Εξάμηνο - κατ: ΔΠΣ', 6, N'ΝΚΓΕ2601'),
(225, N'Advanced Computer Themes', N'Προηγμένα Θέματα Πληροφορικής', N'7o Εξάμηνο - κατ: ΔΠΣ', 6, N'(ΔΠΣ)ΗΥ1010'),
(226, N'Electronic Criminology', N'Ηλεκτρονική Εγκληματολογία', N'7o Εξάμηνο - κατ: ΔΠΣ', 6, N'(ΔΠΣ)ΗΥ2001'),
(227, N'Development of Computer Applications', N'Ανάπτυξη Υπολογιστικών Εφαρμογών', N'7o Εξάμηνο - κατ: ΔΠΣ', 6, N'(ΔΠΣ)ΗΥ2002'),
(228, N'Graphics', N'Γραφικά', N'7o Εξάμηνο - κατ: ΔΠΣ', 6, N'(ΔΠΣ)ΗΥ2000'),
(229, N'Visual Programming - Interface Design', N'Οπτικός Προγραμματισμός - Σχεδίαση Διεπαφών', N'7o Εξάμηνο - κατ: ΔΠΣ', 6, N'(ΔΠΣ)ΓΕ500'),
(230, N'Application Development on the Internet', N'Ανάπτυξη Εφαρμογών στο Διαδίκτυο', N'7o Εξάμηνο - κατ: ΔΠΣ', 6, N'(ΔΠΣ)ΓΕ501'),
(231, N'Financial', N'Οικονομική', N'1o Εξάμηνο - κατ: ΔΕΜ', 5, N'ΝΚΟΙ3100'),
(232, N'Business Economics', N'Οικονομική των Επιχειρήσεων', N'1o Εξάμηνο - κατ: ΔΕΜ', 5, N'ΝΚΟΙ3203'),
(233, N'Mathematics in Management', N'Μαθηματικά στη Διοίκηση', N'1o Εξάμηνο - κατ: ΔΕΜ', 5, N'ΝΚΜΑ0401'),
(234, N'Financial Accounting I', N'Χρηματοοικονομική Λογιστική Ι', N'1o Εξάμηνο - κατ: ΔΕΜ', 5, N'NKΛΟ1201'),
(235, N'Information Technology', N'Τεχνολογία Πληροφορικής', N'1o Εξάμηνο - κατ: ΔΕΜ', 5, N'NKΗΥ0300'),
(236, N'Business Statistics', N'Στατιστική Επιχειρήσεων', N'1o Εξάμηνο - κατ: ΔΕΜ', 5, N'ΝΚΣΤ0300 '),
(237, N'Statistical Forecasting Methods', N'Στατιστικές Μέθοδοι Πρόβλεψης', N'2o Εξάμηνο - κατ: ΔΕΜ', 5, N'ΝΚΣΤ401'),
(238, N'Databases', N'Βάσεις Δεδομένων', N'2o Εξάμηνο - κατ: ΔΕΜ', 5, N'ΝΚΗΥ1006'),
(239, N'Marketing principles', N'Αρχές Marketing', N'2o Εξάμηνο - κατ: ΔΕΜ', 5, N'ΝΚΜΑ4001'),
(240, N'Financial Accounting II', N'Χρηματοοικονομική Λογιστική ΙΙ', N'2o Εξάμηνο - κατ: ΔΕΜ', 5, N'ΝΚΛΟ1202'),
(241, N'Foreign Language - English Terminology', N'Ξένη γλώσσα - Αγγλική Ορολογία', N'2o Εξάμηνο - κατ: ΔΕΜ', 5, N'(ΔΕΜ)ΓΕ1900'),
(242, N'Information and Communication Management', N'Πληροφορία και Διαχείριση της Επικοινωνίας', N'2o Εξάμηνο - κατ: ΔΕΜ', 5, N'(ΔΕΜΔΠΣ)ΔΕ5000'),
(243, N'Human resource Management', N'Διοίκηση Ανθρώπινων Πόρων', N'3o Εξάμηνο - κατ: ΔΕΜ', 5, N'NKΕ1600'),
(244, N'Project management', N'Διαχείριση Έργων', N'3o Εξάμηνο - κατ: ΔΕΜ', 5, N'ΝΚΓΕ1803'),
(245, N'Consumers behavior', N'Συμπεριφορά Καταναλωτή', N'3o Εξάμηνο - κατ: ΔΕΜ', 5, N'ΝΚΓΕ2800'),
(246, N'Management Information Systems', N'Συστήματα Πληροφοριών Διοίκησης ', N'3o Εξάμηνο - κατ: ΔΕΜ', 5, N' ΝΚΗΥ0501'),
(247, N'Supply Chain Management', N'Διοίκηση Εφοδιαστικής Αλυσίδας ', N'3o Εξάμηνο - κατ: ΔΕΜ', 5, N' ΝΚΔΕ4000'),
(248, N'Administrative Accounting I.', N'Διοικητική Λογιστική Ι ', N'3o Εξάμηνο - κατ: ΔΕΜ', 5, N'(ΔΕΜ)ΛΟ1501'),
(249, N'Financial management', N'Χρηματοοικονομική Διοίκηση', N'4o Εξάμηνο - κατ: ΔΕΜ', 5, N'ΝΚΧΡ4002'),
(250, N'Management in the Public Sector', N'Μάνατζμεντ στο Δημόσιο Τομέα ', N'4o Εξάμηνο - κατ: ΔΕΜ', 5, N' NKΔΕ0000'),
(251, N'EBusiness', N'Ηλεκτρονικό Επιχειρείν', N'4o Εξάμηνο - κατ: ΔΕΜ', 5, N'ΝΚΗΥ901'),
(252, N'Total Quality Management - Quality Control', N'Διοίκηση Ολικής Ποιότητας - Ποιοτικός Έλεγχος ', N'4o Εξάμηνο - κατ: ΔΕΜ', 5, N'ΝΚΓΕ3202'),
(253, N'Entrepreneurship', N'Επιχειρηματικότητα', N'4o Εξάμηνο - κατ: ΔΕΜ', 5, N'ΝΚΓΕ2200'),
(254, N'International Economic Relations', N'Διεθνείς Οικονομικές Σχέσεις', N'4o Εξάμηνο - κατ: ΔΕΜ', 5, N'(ΔΕ)ΟΙ3300 '),
(255, N'Strategic Management', N'Στρατηγική Διοίκηση', N'5o Εξάμηνο - κατ: ΔΕΜ', 6, N'ΝΚΔΕ1700'),
(256, N'Marketing Services', N'Marketing Υπηρεσιών', N'5o Εξάμηνο - κατ: ΔΕΜ', 6, N'(ΜΚ)ΓΕ2905'),
(257, N'Innovation Management', N'Διαχείριση Καινοτομιών', N'5o Εξάμηνο - κατ: ΔΕΜ', 6, N'(ΔΕ)ΓΕ3900'),
(258, N'Funding and Evaluation of Investment Plans', N'Χρηματοδότηση και Αξιολόγηση Επενδυτικών Σχεδίων', N'5o Εξάμηνο - κατ: ΔΕΜ', 6, N'(ΔΕ)ΧΡ4001'),
(259, N'Organisational Behaviour', N'Οργανωσιακή Συμπεριφορά', N'5o Εξάμηνο - κατ: ΔΕΜ', 6, N'(ΔΕ)ΓΕ1800'),
(260, N'Commercial law', N'Εμπορικό Δίκαιο', N'6o Εξάμηνο - κατ: ΔΕΜ', 5, N'NKΔΙ0301'),
(261, N'European Integration', N'Ευρωπαϊκή Ολοκλήρωση', N'6o Εξάμηνο - κατ: ΔΕΜ', 5, N'(ΔΕΜ)ΔΙ0501'),
(262, N'Knowledge management', N'Διαχείριση Γνώσης', N'6o Εξάμηνο - κατ: ΔΕΜ', 5, N'(ΔΕ)ΓΕ1801'),
(263, N'Administrative Accounting II', N'Διοικητική Λογιστική ΙΙ', N'6o Εξάμηνο - κατ: ΔΕΜ', 5, N'(ΔΕ)ΛΟ1402'),
(264, N'Financial Modeling', N'Χρηματοοικονομική Μοντελοποίηση', N'6o Εξάμηνο - κατ: ΔΕΜ', 5, N'(ΔΕ)ΧΡ3400'),
(265, N'Management of Production Systems', N'Διοίκηση Παραγωγικών Συστημάτων', N'6o Εξάμηνο - κατ: ΔΕΜ', 5, N'(ΔΕ)ΔΕ4001'),
(266, N'SEMINAR OF UNDERGRADUATE - SCIENTIFIC RESEARCH METHODOLOGY', N'Σεμινάριο Τελειοφοίτων - Μεθοδολογία Επιστιμονικής Έρευνας', N'7o Εξάμηνο - κατ: ΔΕΜ', 6, N'ΝΚΓΕ2601 '),
(267, N'Corporate Responsibility & Ethics', N'Εταιρική Ευθύνη & Ηθική', N'7o Εξάμηνο - κατ: ΔΕΜ', 6, N'(ΔΕΜ)ΓΕ3401'),
(268, N'Labor law', N'Εργατικό Δίκαιο', N'7o Εξάμηνο - κατ: ΔΕΜ', 6, N'(ΔΕ)ΔΙ401'),
(269, N'Market Research', N'Έρευνα Αγοράς', N'7o Εξάμηνο - κατ: ΔΕΜ', 6, N'(ΔΕΜ)ΓΕ2902'),
(270, N'Special Topics in Finance', N'Ειδικά Θέματα Χρηματοοικονομικής', N'7o Εξάμηνο - κατ: ΔΕΜ', 6, N'(ΔΕ)ΧΡ6000'),
(271, N' Application Development on the Internet', N'Ανάπτυξη Εφαρμογών στο Διαδίκτυο (Κατ: ΔΠΣ)', N'7o Εξάμηνο', 6, N' (ΔΠΣ)ΓΕ501'),
(272, N'Electronic Criminology', N'Ηλεκτρονική Εγκληματολογία (Κατ: ΔΠΣ)', N'7o Εξάμηνο', 6, N'(ΔΠΣ)ΗΥ2001'),
(273, N'ACCOUNTING II', N'ΛΟΓΙΣΤΙΚΗ ΙΙ', N'2o Εξάμηνο - Παλαιό Δ.Π', 0, N'N/A'),
(274, N'ACCOUNTING I', N'ΛΟΓΙΣΤΙΚΗ Ι', N'1o Εξάμηνο - Παλαιό Δ.Π', 0, N'N/A'),
(275, N'NETWORKS OF COMPUTERS I.', N'ΔΙΚΤΥΑ ΥΠΟΛΟΓIΣΤΩΝ Ι', N'5o Εξάμηνο - Παλαιό Δ.Π', 0, N'N/A'),
(276, N'COMPUTER NETWORKS II', N'ΔΙΚΤΥΑ ΥΠΟΛΟΓΣΤΩΝ ΙΙ', N'6o Εξάμηνο - Παλαιό Δ.Π', 0, N'N/A'),
(277, N'TEACHING AND PEDAGOGICAL DATA', N'ΣΤΟΙΧΕΙΑ ΔΙΔΑΚΤΙΚΗΣ ΚΑΙ ΠΑΙΔΑΓΩΓΙΚΗΣ', N'4o Εξάμηνο - Παλαιό Δ.Π', 0, N'N/A'),
(278, N'BUSINESS-ADMINISTRATION OF SMALL AND MEDIUM-SIZED ENTERPRISES', N'ΕΠΙΧΕΙΡΗΜΑΤΙΚΟΤΗΤΑ-ΔΙΟΙΚΗΣΗ ΜΙΚΡΟΜΕΣΑΙΩΝ ΕΠΙΧΕΙΡΗΣΕΩΝ', N'4o Εξάμηνο - Παλαιό Δ.Π', 0, N'N/A'),
(279, N'INFORMATION MANAGEMENT ON THE INTERNET', N'ΔΙΑΧΕΙΡΙΣΗ ΠΛΗΡΟΦΟΡΙΩΝ ΣΤΟ ΔΙΑΔΙΚΤΥΟ', N'3o Εξάμηνο - Παλαιό Δ.Π', 0, N'N/A'),
(280, N'introduction to Computer Science', N'ΕΙΣΑΓΩΓΗ ΣΤΗΝ ΠΛΗΡΟΦΟΡΙΚΗ', N'1o Εξάμηνο - Παλαιό Δ.Π', 0, N'N/A'),
(281, N'OBJECTIVE PROGRAMMING', N'ΑΝΤΙΚΕΙΜΕΝΟΣΤΡΕΦΗΣ ΠΡΟΓΡΑΜΜΑΤΙΣΜΟΣ', N'6o Εξάμηνο - Παλαιό Δ.Π', 0, N'N/A'),
(282, N'data structures', N'ΔΟΜΕΣ ΔΕΔΟΜΕΝΩΝ', N'6o Εξάμηνο - Παλαιό Δ.Π', 0, N'N/A'),
(283, N'PRIVATE ECONOMY', N'ΙΔΙΩΤΙΚΗ ΟΙΚΟΝΟΜΙΚΗ', N'1o Εξάμηνο - Παλαιό Δ.Π', 0, N'N/A'),
(284, N'EUROPEAN INSTITUTIONS AND CULTURE', N'ΕΥΡΩΠΑΙΚΟΙ ΘΕΣΜΟΙ ΚΑΙ ΠΟΛΙΤΙΣΜΟΣ', N'6o Εξάμηνο - Παλαιό Δ.Π', 0, N'N/A'),
(285, N'ECONOMIC', N'ΟΙΚΟΝΟΜΙΚΗ', N'1o Εξάμηνο - Παλαιό Δ.Π', 0, N'N/A'),
(286, N'COMPUTER ARCHITECTURE', N'ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΥΠΟΛΟΓΙΣΤΩΝ', N'1o Εξάμηνο - Παλαιό Δ.Π', 0, N'N/A'),
(287, N'ELECTRONIC CRIME', N'ΗΛΕΚΤΡΟΝΙΚΗ ΕΓΚΛΗΜΑΤΟΛΟΓΙΑ', N'N/A', 0, N'N/A'),
(288, N'FINANCIAL ANALYSIS & EVALUATION OF ENTERPRISES', N'ΧΡΗΜΑΤΟΟΙΚΟΝΟΜΙΚΗ ΑΝΑΛΥΣΗ & ΑΠΟΤΙΜΗΣΗ ΕΠΙΧΕΙΡΗΣΕΩΝ', N'4o Εξάμηνο - Παλαιό Δ.Π', 0, N'N/A'),
(289, N'SEMINAR OF UNDERGRADUATE - SCIENTIFIC RESEARCH METHODOLOGY', N'ΣΕΜΙΝΑΡΙΟ ΤΕΛΕΙΟΦΟΙΤΩΝ - ΜΕΘΟΔΟΛΟΓΙΑ ΕΠΙΣΤΗΜΟΝΙΚΗΣ ΕΡΕΥΝΑΣ', N'7o Εξάμηνο - Παλαιό Δ.Π', 0, N'N/A'),
(290, N'INFORMATION AND MANAGEMENT OF COMMUNICATION', N'ΠΛΗΡΟΦΟΡΙΑ ΚΑΙ ΔΙΑΧΕΙΡΙΣΗ ΤΗΣ ΕΠΙΚΟΙΝΩΝΙΑΣ', N'2o Εξάμηνο - Παλαιό Δ.Π', 0, N'N/A'),
(291, N'business Administration', N'ΔΙΟΙΚΗΣΗ ΕΠΙΧΕΙΡΗΣΕΩΝ', N'2o Εξάμηνο - Παλαιό Δ.Π', 0, N'N/A'),
(292, N'human resources management', N'ΔΙΑΧΕΙΡΙΣΗ ΑΝΘΡΩΠΙΝΩΝ ΠΟΡΩΝ', N'3o Εξάμηνο - Παλαιό Δ.Π', 0, N'N/A'),
(293, N'DATABASES I', N'ΒΑΣΕΙΣ ΔΕΔΟΜΕΝΩΝ Ι', N'2o Εξάμηνο - Παλαιό Δ.Π', 0, N'N/A'),
(294, N'EXPERIENCE SYSTEMS AND SUPPORT SYSTEMS', N'ΕΜΠΕΙΡΑ ΣΥΣΤΗΜΑΤΑ ΚΑΙ ΣΥΣΤΗΜΑΤΑ ΥΠΟΣΤΗΡΙΞΗΣ ΑΠΟΦΑΣΕΩΝ', N'5o Εξάμηνο - Παλαιό Δ.Π', 0, N'N/A'),
(295, N'SUPPLY', N'ΕΦΟΔΙΑΣΤΙΚΗ', N'3o Εξάμηνο - Παλαιό Δ.Π', 0, N'N/A'),
(296, N'PROJECT MANAGEMENT', N'ΔΙΑΧΕΙΡΙΣΗ ΕΡΓΩΝ', N'3o Εξάμηνο - Παλαιό Δ.Π', 0, N'N/A'),
(297, N'GRAPHICS', N'ΓΡΑΦΙΚΑ', N'7o Εξάμηνο - Παλαιό Δ.Π', 0, N'N/A'),
(298, N'OPTICAL PROGRAMMING - DRAWING DRAWINGS', N'ΟΠΤΙΚΟΣ ΠΡΟΓΡΑΜΜΑΤΙΣΜΟΣ – ΣΧΕΔΙΑΣΗ ΔΙΕΠΑΦΩΝ', N'7o Εξάμηνο - Παλαιό Δ.Π', 0, N'N/A'),
(299, N'ELECTRONIC OPERATIONAL ACTION', N'ΗΛΕΚΤΡΟΝΙΚΗ ΕΠΙΧΕΙΡΗΣΙΑΚΗ ΔΡΑΣΗ', N'4o Εξάμηνο - Παλαιό Δ.Π', 0, N'N/A'),
(300, N'ADMINISTRATIVE ADMINISTRATIVE SYSTEMS', N'ΠΛΗΡΟΦΟΡΙΑΚΑ ΣΥΣΤΗΜΑΤΑ ΔΙΟΙΚΗΣΗΣ', N'3o Εξάμηνο - Παλαιό Δ.Π', 0, N'N/A'),
(301, N'MARKETING OF INFORMATION', N'ΜΑΡΚΕΤΙΝΓΚ ΤΗΣ ΠΛΗΡΟΦΟΡΙΑΣ', N'2o Εξάμηνο - Παλαιό Δ.Π', 0, N'N/A'),
(302, N'ANALYSIS AND DESIGN OF ALGORITHMS', N'ΑΝΑΛΥΣΗ ΚΑΙ ΣΧΕΔΙΑΣΗ ΑΛΓΟΡΙΘΜΩΝ', N'5o Εξάμηνο - Παλαιό Δ.Π', 0, N'N/A'),
(303, N'MULTIMEDIA IN INFORMATION MANAGEMENT', N'ΠΟΛΥΜΕΣΑ ΣΤΗ ΔΙΑΧΕΙΡΙΣΗ ΠΛΗΡΟΦΟΡΙΩΝ', N'4o Εξάμηνο - Παλαιό Δ.Π', 0, N'N/A'),
(304, N'DATABASES II', N'ΒΑΣΕΙΣ ΔΕΔΟΜΕΝΩΝ ΙΙ', N'3o Εξάμηνο - Παλαιό Δ.Π', 0, N'N/A'),
(305, N'ADVANCED IT ISSUES', N'ΠΡΟΗΓΜΕΝΑ ΘΕΜΑΤΑ ΠΛΗΡΟΦΟΡΙΚΗΣ', N'7o Εξάμηνο - Παλαιό Δ.Π', 0, N'N/A'),
(306, N'SYSTEM ANALYSIS - SOFTWARE TECHNOLOGY', N'ΑΝΑΛΥΣΗ ΣΥΣΤΗΜΑΤΩΝ – ΤΕΧΝΟΛΟΓΙΑ ΛΟΓΙΣΜΙΚΟΥ', N'6o Εξάμηνο - Παλαιό Δ.Π', 0, N'N/A'),
(307, N'SPECIAL QUESTIONS OF LAW', N'ΕΙΔΙΚΑ ΘΕΜΑΤΑ ΔΙΚΑΙΟΥ', N'4o Εξάμηνο - Παλαιό Δ.Π', 0, N'N/A'),
(308, N'OPERATING SYSTEMS', N'ΛΕΙΤΟΥΡΓΙΚΑ ΣΥΣΤΗΜΑΤΑ', N'2o Εξάμηνο - Παλαιό Δ.Π', 0, N'N/A'),
(309, N'STATISTICAL ENTERPRISES', N'ΣΤΑΤΙΣΤΙΚΗ ΕΠΙΧΕΙΡΗΣΕΩΝ', N'1o Εξάμηνο - Παλαιό Δ.Π', 0, N'N/A'),
(310, N'TOTAL QUALITY MANAGEMENT', N'ΟΛΙΚΗ ΔΙΑΧΕΙΡΙΣΗ ΠΟΙΟΤΗΤΑΣ', N'4o Εξάμηνο - Παλαιό Δ.Π', 0, N'N/A'),
(311, N'SENIOR SEMINAR', N'ΣΕΜΙΝΑΡΙΟ ΤΕΛΕΙΟΦΟΙΤΩΝ', N'7o Εξάμηνο - Παλαιό Δ.Π', 0, N'N/A'),
(312, N'operational research', N'ΕΠΙΧΕΙΡΗΣΙΑΚΗ ΕΡΕΥΝΑ', N'6o Εξάμηνο - Παλαιό Δ.Π', 0, N'N/A'),
(313, N'MATHEMATICS IN ADMINISTRATION', N'ΜΑΘΗΜΑΤΙΚΑ ΣΤΗ ΔΙΟΙΚΗΣΗ', N'1o Εξάμηνο - Παλαιό Δ.Π', 0, N'N/A'),
(314, N'STATISTICAL PROBLEM METHODS', N'ΣΤΑΤΙΣΤΙΚΕΣ ΜΕΘΟΔΟΙ ΠΡΟΒΛΕΨΗΣ', N'2o Εξάμηνο - Παλαιό Δ.Π', 0, N'N/A'),
(315, N'STRUCTURED PROGRAMMING', N'ΔΟΜΗΜΕΝΟΣ ΠΡΟΓΡΑΜΜΑΤΙΣΜΟΣ', N'5o Εξάμηνο - Παλαιό Δ.Π', 0, N'N/A'),
(316, N'Discrete Mathematics - Linear Algebra', N'ΔΙΑΚΡΙΤΑ ΜΑΘΗΜΑΤΙΚΑ-ΓΡΑΜΜΙΚΗ ΑΛΓΕΒΡΑ', N'5o Εξάμηνο - Παλαιό Δ.Π', 0, N'N/A');

SET IDENTITY_INSERT[dbo].[Lessons] OFF
